dbt_unit_tests:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 6
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
  target: dev
